import Head from 'next/head'
import React from "react";
// import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { AudioPlayer } from '@/components/AudioPlayer'
// import { background } from "http://localhost:3000/trees.jpg";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>React Audio Player</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <style>
        @import url('https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;400;500;600;700&display=swap');
        </style>
      </Head>
      <main className={styles.body}>
      
            <div className={styles.fixed_header}>
            <header className={styles.headah}>
              <h1>TROVE</h1>
            </header> 
            </div> 

            <div className={styles.body_box}>
              <div className={styles.bodeuah}>
                  <p>Body!</p>
              </div>
            </div>
            
            <div className={styles.fixed_footer}>
              <footer className={styles.footah}>
                  <AudioPlayer/>


                  {/* <div className={styles.songahrt}></div>
                  <div className={styles.playppause}></div>
                  <div className={styles.playahControlz}></div> */}
              </footer> 
            </div>
            
            
        

      </main>
    </>
  )
}
